### ISSUE TITLE
 compile error

### ISSUE THREAD

**Issue by chiaqi** [StefanoBoriero/ebpfRos#3]
ubuntu22.04   go 1.22.4  llvm 18  bpftool source code install

node_creation_counter.bpf.c:14:5: error: incomplete definition of type 'struct pt_regs'
   14 | int BPF_KPROBE(nodeCreationCount, void *context, const char *name, const char *namespace) {
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/bpf/bpf_tracing.h:429:20: note: expanded from macro 'BPF_KPROBE'
  429 |         return ____##name(___bpf_kprobe_args(args));                        \
      |                           ^~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/bpf/bpf_tracing.h:409:2: note: expanded from macro '___bpf_kprobe_args'
  409 |         ___bpf_apply(___bpf_kprobe_args, ___bpf_narg(args))(args)
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/bpf/bpf_helpers.h:165:29: note: expanded from macro '___bpf_apply'
  165 | #define ___bpf_apply(fn, n) ___bpf_concat(fn, n)
      |                             ^
note: (skipping 1 expansions in backtrace; use -fmacro-backtrace-limit=0 to see all)
<scratch space>:26:1: note: expanded from here
   26 | ___bpf_kprobe_args3
      | ^
/usr/include/bpf/bpf_tracing.h:403:37: note: expanded from macro '___bpf_kprobe_args3'
  403 |         ___bpf_kprobe_args2(args), (void *)PT_REGS_PARM3(ctx)
      |                                            ^~~~~~~~~~~~~~~~~~
/usr/include/bpf/bpf_tracing.h:115:30: note: expanded from macro 'PT_REGS_PARM3'
  115 | #define PT_REGS_PARM3(x) ((x)->rdx)
      |                           ~~~^
/usr/include/bpf/bpf_helper_defs.h:22:8: note: forward declaration of 'struct pt_regs'
   22 | struct pt_regs;

/root/hy-wk/ebpfRos/node_creation_counter.bpf.c:21:3: error: use of undeclared identifier 'u32'
   21 |   u32 pid = bpf_get_current_pid_tgid() >> 32;
      |   ^
/root/hy-wk/ebpfRos/node_creation_counter.bpf.c:22:3: error: use of undeclared identifier 'u32'
   22 |   u32 uid = bpf_get_current_uid_gid() & 0xffffffff;
      |   ^
/root/hy-wk/ebpfRos/node_creation_counter.bpf.c:23:15: error: use of undeclared identifier 'pid'
   23 |   data->pid = pid;
      |               ^
/root/hy-wk/ebpfRos/node_creation_counter.bpf.c:24:15: error: use of undeclared identifier 'uid'
   24 |   data->uid = uid;
      |               ^
/root/hy-wk/ebpfRos/node_creation_counter.bpf.c:29:37: error: use of undeclared identifier 'pid'
   29 |   bpf_map_update_elem(&pidNodeMap, &pid, data, BPF_ANY);
      |                                     ^
/root/hy-wk/ebpfRos/node_creation_counter.bpf.c:29:48: error: use of undeclared identifier 'BPF_ANY'
   29 |   bpf_map_update_elem(&pidNodeMap, &pid, data, BPF_ANY);
      |                                                ^
13 errors generated.
Error: can't execute clang: exit status 1

**Comment by chiaqi** [comment]
For different kernel versions, add different header files.
close this issue

**Comment by stefanoboriero** [comment]
Apologies for not getting back to you, I have little time to dedicate to this. The status of the project is experimental so I can't make any promise around its stability, thanks for sharing the issue and the workaround :bow:
